spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url:  jdbc:mysql://localhost:3306/ALG_DB?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 104857600
      max-request-size: 10485760
logging:
  file:  /var/tomcat/algsystem.log
